### ISSUE TITLE
cannot declare variable 'Serial9b1' to be of abstract type 'HardwareSerial9b'

### ISSUE THREAD

**Issue by ouyangxin95** [jorticus/Arduino-Serial9b#1]
D:\Program Files\arduino-1.8.3\libraries\Serial9b/Serial9b.h:127:25: error: cannot declare variable 'Serial9b1' to be of abstract type 'HardwareSerial9b'

 extern HardwareSerial9b Serial9b1;

                         ^

D:\Program Files\arduino-1.8.3\libraries\Serial9b/Serial9b.h:85:7: note:   because the following virtual functions are pure within 'HardwareSerial9b':

 class HardwareSerial9b : public HardwareSerial, public Stream9b

**Comment by jorticus** [comment]
Can you try checking out an older commit (91e8e93a8a)? That commit is before I reworked things with virtual functions

**Comment by PeterW-avr** [comment]
This stuff still does not compile, the whole thing is for nothing. :-(

**Comment by jorticus** [comment]
Probably all that it needs is to figure out what Arduino have added to the HardwareSerial class, then implement those new functions in Serial9b. The error message above is just saying that some of the parent classes methods haven't been implemented, and I don't control the parent class.

I don't have time to look at this but anyone familiar with C++ and inheritance should be able to make quick work of it. Otherwise I'll fix when I next need this (possibly never)
